"""Workday scraper.

Workday powers ~15-20% of Fortune 500 careers pages including most major
consultancies (Deloitte, PwC, EY, KPMG), banks (JPMorgan, Capital One,
Wells Fargo), and large enterprise (Salesforce, ServiceNow, Cisco, Adobe).

Endpoint pattern:
  POST https://{tenant}.{pod}.myworkdayjobs.com/wday/cxs/{tenant}/{board}/jobs
  Headers: Accept: application/json, Content-Type: application/json
  Body: {"appliedFacets": {}, "limit": 20, "offset": 0, "searchText": "<keyword>"}

  Response: {
    "total": <int>,
    "jobPostings": [
      {
        "title": "...",
        "locationsText": "...",
        "postedOn": "Posted Yesterday|3 Days Ago|...",
        "externalPath": "/job/USA-Washington-DC/...",
        "bulletFields": [...]
      }, ...
    ]
  }

JD body (separate request):
  GET https://{tenant}.{pod}.myworkdayjobs.com/wday/cxs/{tenant}/{board}{externalPath}
"""
from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from backend.models import Role
from backend.scraper.base import BaseScraper
from backend.scraper.greenhouse import _strip_html


# Curated Workday tenants — VERIFIED WORKING via test calls.
# Each entry: (display_name, base_url, board_path)
# Each represents an actual confirmed Workday API endpoint we can hit.
# Add new tenants only after verifying with a test POST returns 200.
WORKDAY_TENANTS: list[tuple[str, str, str]] = [
    # 40 verified working tenants (auto-generated by scripts/verify_workday_smart.py
    # 2026-05-02). Each was confirmed by POSTing the actual Workday search API
    # with searchText="manager" and counting >0 jobs returned. Sectors: Big 4
    # (PwC, BDO), consulting (Accenture, Booz Allen, BDO), banks (Citi, PNC,
    # Capital One, Truist, Visa, Mastercard, Morgan Stanley, BlackRock),
    # insurance (Travelers, AIG, Allstate, Prudential), federal contractors
    # (Leidos, Booz Allen, CACI, GDIT, Boeing), pharma (Eli Lilly, Pfizer,
    # Gilead, Amgen, McKesson), retail (Target, Walmart, CarMax), tech (Adobe,
    # Salesforce, Intel, HP, Cisco, T-Mobile), telecom (Comcast), real estate
    # (JLL), industrials (3M, Old Dominion), media (Disney), policy (RAND).
    ("Accenture",          "https://accenture.wd103.myworkdayjobs.com",        "AccentureCareers"),
    ("Citi",               "https://citi.wd5.myworkdayjobs.com",               "2"),
    ("PNC",                "https://pnc.wd5.myworkdayjobs.com",                "External"),
    ("Walmart",            "https://walmart.wd5.myworkdayjobs.com",            "WalmartExternal"),
    ("PwC",                "https://pwc.wd3.myworkdayjobs.com",                "Global_Experienced_Careers"),
    ("Leidos",             "https://leidos.wd5.myworkdayjobs.com",             "External"),
    ("Booz Allen",         "https://bah.wd1.myworkdayjobs.com",                "BAH_Jobs"),
    ("JLL",                "https://jll.wd1.myworkdayjobs.com",                "jllcareers"),
    ("T-Mobile",           "https://tmobile.wd1.myworkdayjobs.com",            "External"),
    ("Amgen",              "https://amgen.wd1.myworkdayjobs.com",              "Careers"),
    ("Adobe",              "https://adobe.wd5.myworkdayjobs.com",              "external_experienced"),
    ("Capital One",        "https://capitalone.wd12.myworkdayjobs.com",        "Capital_One"),
    ("Truist",             "https://truist.wd1.myworkdayjobs.com",             "Careers"),
    ("CarMax",             "https://carmax.wd1.myworkdayjobs.com",             "External"),
    ("Visa",               "https://visa.wd5.myworkdayjobs.com",               "Visa"),
    ("Eli Lilly",          "https://lilly.wd5.myworkdayjobs.com",              "LLY"),
    ("GDIT",               "https://gdit.wd5.myworkdayjobs.com",               "External_Career_Site"),
    ("Boeing",             "https://boeing.wd1.myworkdayjobs.com",             "External_Careers"),
    ("Intel",              "https://intel.wd1.myworkdayjobs.com",              "External"),
    ("Mastercard",         "https://mastercard.wd1.myworkdayjobs.com",         "CorporateCareers"),
    ("Prudential",         "https://prudential.wd3.myworkdayjobs.com",         "Prudential"),
    ("Salesforce",         "https://salesforce.wd12.myworkdayjobs.com",        "External_Career_Site"),
    ("Morgan Stanley",     "https://ms.wd5.myworkdayjobs.com",                 "External"),
    ("3M",                 "https://3m.wd1.myworkdayjobs.com",                 "Search"),
    ("Pfizer",             "https://pfizer.wd1.myworkdayjobs.com",             "PfizerCareers"),
    ("Allstate",           "https://allstate.wd5.myworkdayjobs.com",           "Allstate_Careers"),
    ("Target",             "https://target.wd5.myworkdayjobs.com",             "targetcareers"),
    ("Travelers",          "https://travelers.wd5.myworkdayjobs.com",          "External"),
    ("CACI",               "https://caci.wd1.myworkdayjobs.com",               "External"),
    ("Gilead",             "https://gilead.wd1.myworkdayjobs.com",             "gileadcareers"),
    ("McKesson",           "https://mckesson.wd3.myworkdayjobs.com",           "External_Careers"),
    ("Disney",             "https://disney.wd5.myworkdayjobs.com",             "disneycareer"),
    ("AIG",                "https://aig.wd1.myworkdayjobs.com",                "aig"),
    ("Old Dominion",       "https://odfl.wd1.myworkdayjobs.com",               "Odfl_Careers"),
    ("Cisco",              "https://cisco.wd5.myworkdayjobs.com",              "Cisco_Careers"),
    ("HP",                 "https://hp.wd5.myworkdayjobs.com",                 "ExternalCareerSite"),
    ("BlackRock",          "https://blackrock.wd1.myworkdayjobs.com",          "BlackRock_Professional"),
    ("Comcast",            "https://comcast.wd5.myworkdayjobs.com",            "Comcast_Careers"),
    ("BDO",                "https://bdo.wd3.myworkdayjobs.com",                "Bdo"),
    ("RAND Corporation",   "https://rand.wd5.myworkdayjobs.com",               "External_Career_Site"),
    # Discovered 2026-05-03 via Playwright XHR capture (workday_discover.py)
    ("Merck",              "https://msd.wd5.myworkdayjobs.com",                "SearchJobs"),
    # Discovered 2026-05-03 via load-time XHR capture (workday_discover_v2.py)
    ("State Street",       "https://statestreet.wd1.myworkdayjobs.com",        "Global"),
]

# Tenants STILL FAILING after smart cluster-debug verification (2026-05-02):
#   Deloitte, EY, KPMG, JPMorgan, Goldman Sachs, Wells Fargo, BoA, US Bank,
#   Liberty Mutual, MetLife, PepsiCo, Coca-Cola, P&G, Mondelez, Kroger,
#   Costco, Microsoft, Oracle, IBM, SAP, J&J, Merck, BMS, UnitedHealth, CVS,
#   Marriott, Hilton, Delta, United, AA, CBRE, AECOM, etc.
# Their endpoints return 422 (body-shape rejected, but no body variant
# unlocked them) or 404 (URL/board pattern wrong). Both require Playwright-
# based discovery to load the live careers page, intercept the actual XHR
# call, capture auth tokens, and reverse-engineer per-tenant request shape.
# Tracked as a Phase 1.5 / Phase 2 deliverable.


def _parse_posted_on(posted_on: str) -> Optional[str]:
    """Workday returns 'Posted Yesterday', 'Posted 3 Days Ago' etc.
    Convert to ISO date string approximation."""
    if not posted_on:
        return None
    text = posted_on.lower()
    days_ago = 0
    if "today" in text:
        days_ago = 0
    elif "yesterday" in text:
        days_ago = 1
    else:
        m = re.search(r"(\d+)\s+(day|week|month)", text)
        if m:
            n = int(m.group(1))
            unit = m.group(2)
            days_ago = n if unit == "day" else (n * 7 if unit == "week" else n * 30)
    posted = datetime.now(timezone.utc) - timedelta(days=days_ago)
    return posted.isoformat()


class WorkdayScraper(BaseScraper):
    source_name = "Workday"

    async def search(
        self,
        *,
        keywords: list[str],
        limit_per_keyword: int = 50,
        posted_within_days: Optional[int] = 30,
    ) -> list[Role]:
        # Workday tenants are independent — fan out across all tenants × keywords
        # Concurrency cap (max 12 in-flight) prevents the whole pipeline from
        # stalling when 1-2 slow tenants would otherwise hold up `gather()`.
        # Per-tenant-keyword timeout (45s wall-clock) ensures one slow tenant
        # can't hang the entire run for 30+ minutes.
        sem = asyncio.Semaphore(12)

        async def bounded(display_name, base_url, board, kw):
            async with sem:
                try:
                    return await asyncio.wait_for(
                        self._search_tenant_keyword(
                            display_name, base_url, board, kw, limit_per_keyword
                        ),
                        timeout=45.0,
                    )
                except asyncio.TimeoutError:
                    return []

        tasks = []
        for display_name, base_url, board in WORKDAY_TENANTS:
            for kw in keywords:
                tasks.append(bounded(display_name, base_url, board, kw))
        results = await asyncio.gather(*tasks, return_exceptions=True)

        cutoff = (
            datetime.now(timezone.utc) - timedelta(days=posted_within_days)
            if posted_within_days else None
        )

        all_roles: list[Role] = []
        seen_url: set[str] = set()
        seen_title_company: set[tuple[str, str]] = set()

        for result in results:
            if isinstance(result, Exception):
                continue
            for role in result:
                if role.job_url and role.job_url in seen_url:
                    continue
                key = (
                    (role.job_title or "").strip().lower(),
                    (role.company or "").strip().lower(),
                )
                if key[0] and key in seen_title_company:
                    continue
                # Posted-date freshness
                if cutoff and role.posted_date:
                    try:
                        posted = datetime.fromisoformat(role.posted_date.replace("Z", "+00:00"))
                        if posted < cutoff:
                            continue
                    except (ValueError, TypeError):
                        pass
                if role.job_url:
                    seen_url.add(role.job_url)
                seen_title_company.add(key)
                all_roles.append(role)
        return all_roles

    async def _search_tenant_keyword(
        self,
        display_name: str,
        base_url: str,
        board: str,
        keyword: str,
        limit: int,
    ) -> list[Role]:
        """Search one Workday tenant for one keyword."""
        endpoint = f"{base_url}/wday/cxs/{self._tenant_from_url(base_url)}/{board}/jobs"
        roles: list[Role] = []
        offset = 0
        while len(roles) < limit:
            body = {
                "appliedFacets": {},
                "limit": 20,
                "offset": offset,
                "searchText": keyword,
            }
            try:
                response = await self.client._client.post(  # type: ignore[union-attr]
                    endpoint,
                    json=body,
                    headers={
                        "Accept": "application/json",
                        "Content-Type": "application/json",
                        "User-Agent": "Mozilla/5.0",
                    },
                )
            except Exception:
                break
            if response.status_code >= 400:
                break
            try:
                data = response.json()
            except Exception:
                break
            postings = data.get("jobPostings") or []
            if not postings:
                break
            for j in postings:
                try:
                    roles.append(self._posting_to_role(j, display_name, base_url, board))
                except Exception:
                    continue
            if len(postings) < 20:
                break
            offset += 20
        return roles[:limit]

    @staticmethod
    def _tenant_from_url(base_url: str) -> str:
        """Extract tenant name from base URL.
        e.g., 'https://capitalone.wd1.myworkdayjobs.com' -> 'capitalone'.
        """
        from urllib.parse import urlparse
        host = urlparse(base_url).netloc
        # Special case: 'apply.deloitte.com' -> guess 'deloitte'
        if "apply.deloitte.com" in host:
            return "deloitte"
        # Otherwise tenant is the first label
        parts = host.split(".")
        if parts:
            return parts[0]
        return host

    def _posting_to_role(
        self,
        posting: dict[str, Any],
        company: str,
        base_url: str,
        board: str,
    ) -> Role:
        title = posting.get("title") or ""
        external_path = posting.get("externalPath") or ""
        url = f"{base_url}{external_path}" if external_path else ""

        location_text = posting.get("locationsText") or ""
        loc_low = location_text.lower()
        if "remote" in loc_low:
            location_type = "Remote"
        elif "hybrid" in loc_low:
            location_type = "Hybrid"
        else:
            location_type = "On-site"

        posted_iso = _parse_posted_on(posting.get("postedOn") or "")

        # bulletFields sometimes contains salary/job-id
        salary_text = None
        salary_min = None
        salary_max = None
        for field in (posting.get("bulletFields") or []):
            if not field:
                continue
            field_str = str(field)
            if "$" in field_str:
                salary_text = field_str
                # Parse $ amounts so the dashboard shows a range, not just text
                import re as _re
                nums = _re.findall(
                    r"\$?(\d{2,3}(?:,\d{3})+|\d{2,3}[Kk])", field_str,
                )
                parsed: list[int] = []
                for n in nums[:2]:
                    n2 = n.replace(",", "")
                    if n2.lower().endswith("k"):
                        parsed.append(int(float(n2[:-1]) * 1000))
                    else:
                        parsed.append(int(float(n2)))
                if parsed:
                    salary_min = parsed[0]
                    if len(parsed) > 1:
                        salary_max = parsed[1]
                break

        return Role(
            job_title=title,
            company=self._normalize_company(company),
            job_url=url,
            location=location_text or None,
            location_type=location_type,
            job_description_full="",   # JD is fetched lazily — search results don't include
            jd_completeness="Missing",
            salary_text=salary_text,
            salary_min=salary_min,
            salary_max=salary_max,
            posted_date=posted_iso,
            primary_source=self.source_name,
            date_first_seen=datetime.now(timezone.utc).date().isoformat(),
        )

    async def fetch_jd(self, role: Role) -> str:
        """Fetch full JD for a Workday role.

        Two-tier strategy:
          1. CXS JSON detail endpoint (preferred). Returns structured JSON
             with the full JD body — no JavaScript rendering required.
             Endpoint shape: {base_url}/wday/cxs/{tenant}/{board}{externalPath}
          2. Public HTML page fallback. JS-rendered, often returns a stub
             with no JD, but worth trying when CXS fails.

        Audit observation: prior implementation only used (2), giving 34-45%
        JD coverage. Switching to (1) typically pushes coverage to 70-80%
        because Workday's careers pages are SPA-rendered.
        """
        if role.job_description_full:
            return role.job_description_full
        if not role.job_url:
            return ""

        cxs_jd = await self._fetch_jd_via_cxs(role.job_url)
        if cxs_jd:
            return cxs_jd

        # Fallback: public HTML page (often a JS shell, but try anyway)
        try:
            response = await self.client.get(role.job_url)
            return _strip_html(response.text)
        except Exception:
            return ""

    async def _fetch_jd_via_cxs(self, job_url: str) -> str:
        """Fetch JD from Workday's CXS detail endpoint.

        URL transformation:
          input:  https://capitalone.wd12.myworkdayjobs.com/job/USA-VA-Mclean/Engineer_R12345
          output: https://capitalone.wd12.myworkdayjobs.com/wday/cxs/capitalone/Capital_One/job/USA-VA-Mclean/Engineer_R12345

        Returns plain-text JD or "" on any failure (caller falls back).
        """
        try:
            from urllib.parse import urlparse
            parsed = urlparse(job_url)
            host = parsed.netloc
            path = parsed.path
            if not host or not path:
                return ""

            # Find matching tenant config to get the board name
            board: Optional[str] = None
            for _name, base_url, b in WORKDAY_TENANTS:
                base_host = urlparse(base_url).netloc
                if base_host == host:
                    board = b
                    break
            if not board:
                return ""

            # Some Workday URLs embed the board ("/Capital_One/job/..."); strip
            # it so external_path starts with "/job/..." for the CXS endpoint.
            external_path = path
            for prefix in (f"/{board}/", f"/en-US/{board}/"):
                if path.startswith(prefix):
                    external_path = path[len(prefix) - 1:]  # keep leading slash
                    break

            tenant = self._tenant_from_url(f"https://{host}")
            cxs_url = f"https://{host}/wday/cxs/{tenant}/{board}{external_path}"

            resp = await self.client._client.get(  # type: ignore[union-attr]
                cxs_url,
                headers={
                    "Accept": "application/json",
                    "User-Agent": "Mozilla/5.0",
                },
            )
            if resp.status_code != 200:
                return ""
            try:
                data = resp.json()
            except Exception:
                return ""

            # Workday CXS detail response: { "jobPostingInfo": { "jobDescription": "<html>...</html>" } }
            if not isinstance(data, dict):
                return ""
            jd_info = data.get("jobPostingInfo") or {}
            jd_html = jd_info.get("jobDescription") or ""
            if not jd_html:
                return ""
            return _strip_html(jd_html)
        except Exception:
            return ""
