import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Folder, Clock, RotateCcw, Check, DollarSign, AlertTriangle, Loader2, Fingerprint, Copy } from 'lucide-react'
import { toast } from 'sonner'
import { useAppStore } from '@/stores/appStore'
import { ApiError, getAuditFolder, getIdentity, resetAllData, setAuditFolder } from '@/services/api'

// Confirmation phrase the user must type to enable the reset button.
// Picked to be unmistakable and slightly inconvenient — the friction is
// intentional, since the action is irreversible.
const RESET_CONFIRM_PHRASE = 'RESET'

export default function Settings() {
  const cacheMaxAgeDays = useAppStore((s) => s.cacheMaxAgeDays)
  const setCacheMaxAgeDays = useAppStore((s) => s.setCacheMaxAgeDays)
  const hideSalarylessRoles = useAppStore((s) => s.hideSalarylessRoles)
  const setHideSalarylessRoles = useAppStore((s) => s.setHideSalarylessRoles)

  const [folderPath, setFolderPath] = useState<string>('')
  const [folderInput, setFolderInput] = useState<string>('')
  const [savingFolder, setSavingFolder] = useState(false)

  const [resetModalOpen, setResetModalOpen] = useState(false)
  const [resetConfirmInput, setResetConfirmInput] = useState('')
  const [resetting, setResetting] = useState(false)

  // Tester UUID — fetched from /identity on mount. Displayed read-only
  // for the user to copy and share with the operator (Ziad) when filing
  // bug reports or asking for help. The actual UUID is generated by the
  // Rust shim on first launch and lives in app data.
  const [testerId, setTesterId] = useState<string>('')

  useEffect(() => {
    getAuditFolder()
      .then((r) => {
        setFolderPath(r.path)
        setFolderInput(r.path)
      })
      .catch(() => {})
    getIdentity()
      .then((r) => setTesterId(r.tester_uuid || ''))
      .catch(() => {})
  }, [])

  const copyTesterId = async () => {
    if (!testerId) return
    try {
      await navigator.clipboard.writeText(testerId)
      toast.success('Tester ID copied to clipboard')
    } catch {
      toast.error('Could not copy — select and copy manually')
    }
  }

  const saveFolder = async () => {
    if (!folderInput.trim()) return
    setSavingFolder(true)
    try {
      const r = await setAuditFolder(folderInput.trim())
      setFolderPath(r.path)
      toast.success('Audit folder updated')
    } catch (e) {
      toast.error(`Failed to set folder: ${e instanceof Error ? e.message : 'unknown'}`)
    } finally {
      setSavingFolder(false)
    }
  }

  // Reset flow — wipes server-side state, clears the persisted Zustand
  // store, then asks Tauri to relaunch on a fresh process. The relaunch
  // is what makes this feel "like a fresh install" — without it the
  // backend's startup sync hooks would race the user back into a half-
  // hydrated state. Tauri's relaunch() kills both the webview and the
  // bundled FastAPI sidecar, so the next boot reinitializes everything.
  const handleReset = async () => {
    if (resetting) return
    if (resetConfirmInput.trim() !== RESET_CONFIRM_PHRASE) return

    setResetting(true)
    try {
      // 1. Backend: wipe runs.db + audits + diffs and cancel any active run.
      await resetAllData()

      // 2. Frontend: clear Zustand's persisted localStorage entry. We
      // wipe the whole key rather than calling store.reset() so that
      // even non-partialized state (cache settings, salary toggle) is
      // gone — a "true" fresh user wouldn't have those preferences.
      try {
        localStorage.removeItem('job-search-app-state')
      } catch {
        // Private mode / restricted storage. Relaunch will still help
        // most of the way; not worth blocking the reset on this.
      }

      // 3. Tauri: relaunch the app so the bundled backend restarts and
      // the webview reloads from a clean slate. Falls back to a hard
      // page reload if we're not running inside Tauri (browser preview).
      try {
        const { relaunch } = await import('@tauri-apps/plugin-process')
        await relaunch()
      } catch {
        // Non-Tauri context — best effort: reload the webview. The
        // backend stays up but we already wiped its state, so the
        // dashboard will boot empty.
        window.location.reload()
      }
    } catch (e) {
      const msg = e instanceof ApiError ? e.detail : (e instanceof Error ? e.message : 'unknown')
      toast.error(`Reset failed: ${msg}`)
      setResetting(false)
    }
    // Note: no finally{} — on success the app is relaunching and any
    // state update would race the unmount. Only reset `resetting` on
    // the error path above.
  }

  const closeResetModal = () => {
    if (resetting) return
    setResetModalOpen(false)
    setResetConfirmInput('')
  }

  return (
    <div className="px-10 py-8 max-w-3xl mx-auto">
      <h1 className="text-2xl font-semibold tracking-tight">Settings</h1>
      <p className="text-sm text-base-400 mt-1">Where the app saves its data and how aggressively it caches.</p>

      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="mt-8 space-y-6"
      >
        {/* Audit folder */}
        <div className="glass rounded-xl p-6">
          <div className="flex items-center gap-2 mb-3">
            <Folder size={16} className="text-accent-400" />
            <h2 className="text-sm font-medium">Audit folder</h2>
          </div>
          <p className="text-xs text-base-400 mb-4 leading-relaxed">
            All search runs, the role archive (<code className="text-base-200">runs.db</code>), and
            human-readable summaries get saved here. Point this at a folder that syncs to
            OneDrive or Google Drive — that way your audit data is backed up and (if multiple
            testers point to the same parent folder) the app automatically learns from
            everyone's runs.
          </p>
          <div className="flex gap-2">
            <input
              type="text"
              value={folderInput}
              onChange={(e) => setFolderInput(e.target.value)}
              placeholder="C:\Users\you\OneDrive\JobSearchApp\testers\you"
              className="flex-1 px-3 py-2 rounded-lg bg-white/[0.04] border border-white/[0.10]
                         text-sm text-base-100 placeholder:text-base-600
                         focus:outline-none focus:border-accent-500/50"
            />
            <button
              onClick={saveFolder}
              disabled={savingFolder || !folderInput.trim() || folderInput.trim() === folderPath}
              className="px-4 py-2 rounded-lg bg-white text-base-950 text-sm font-medium
                         hover:bg-base-200 transition-colors
                         disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {savingFolder ? 'Saving…' : 'Save'}
            </button>
          </div>
          {folderPath && (
            <p className="text-[11px] text-base-500 mt-2 flex items-center gap-1.5">
              <Check size={11} className="text-tier-strong" />
              Active: <code className="text-base-300">{folderPath}</code>
            </p>
          )}
        </div>

        {/* Cache duration */}
        <div className="glass rounded-xl p-6">
          <div className="flex items-center gap-2 mb-3">
            <Clock size={16} className="text-accent-400" />
            <h2 className="text-sm font-medium">Cache duration</h2>
          </div>
          <p className="text-xs text-base-400 mb-4 leading-relaxed">
            How long results stay cached for the same profile. Repeat searches with unchanged
            keywords/preferences within this window are returned in seconds instead of
            re-running the full 12–25 minute pipeline. Force-refresh on the dashboard
            bypasses the cache.
          </p>
          <div className="flex gap-2">
            {[1, 3, 7, 14, 30].map((days) => (
              <button
                key={days}
                onClick={() => {
                  setCacheMaxAgeDays(days)
                  toast.success(`Cache window set to ${days} days`)
                }}
                className={`px-4 py-2 rounded-lg text-sm transition-colors ${
                  cacheMaxAgeDays === days
                    ? 'bg-accent-500/20 text-accent-200 border border-accent-500/40'
                    : 'glass-subtle hover:bg-white/[0.06] text-base-300 border border-transparent'
                }`}
              >
                {days}d
              </button>
            ))}
          </div>
          <p className="text-[11px] text-base-500 mt-2">
            Cache invalidates automatically if your profile, keywords, or preferences change.
          </p>
        </div>

        {/* Salary visibility toggle */}
        <div className="glass rounded-xl p-6">
          <div className="flex items-center gap-2 mb-3">
            <DollarSign size={16} className="text-accent-400" />
            <h2 className="text-sm font-medium">Hide roles without salary disclosed</h2>
          </div>
          <p className="text-xs text-base-400 mb-4 leading-relaxed">
            By default the dashboard shows all qualifying roles, including ones where the
            employer didn't publish a salary range. Some companies (Big 4, Microsoft, federal)
            consistently leave compensation off the JD. Flip this on to only see roles with
            an explicit pay range.
          </p>
          <div className="flex items-center gap-3">
            <button
              onClick={() => {
                const next = !hideSalarylessRoles
                setHideSalarylessRoles(next)
                toast.success(next ? 'Hiding roles without salary' : 'Showing all roles')
              }}
              role="switch"
              aria-checked={hideSalarylessRoles}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors
                ${hideSalarylessRoles ? 'bg-accent-500' : 'bg-white/10'}`}
            >
              <span
                className={`inline-block h-5 w-5 transform rounded-full bg-white transition-transform
                  ${hideSalarylessRoles ? 'translate-x-5' : 'translate-x-0.5'}`}
              />
            </button>
            <span className="text-sm text-base-300">
              {hideSalarylessRoles ? 'On — only showing roles with salary disclosed' : 'Off — showing all qualifying roles'}
            </span>
          </div>
        </div>

        {/* Tester ID — anonymous UUID generated on first launch. Surfaced
            here so users can share it with the operator for support /
            triage instead of having to dig into their app data folder. */}
        <div className="glass rounded-xl p-6">
          <div className="flex items-center gap-2 mb-3">
            <Fingerprint size={16} className="text-accent-400" />
            <h2 className="text-sm font-medium">Tester ID</h2>
          </div>
          <p className="text-xs text-base-400 mb-4 leading-relaxed">
            Your anonymous identifier — generated automatically on first launch.
            No name, email, or personal info attached. Share this with Ziad if
            you need help with a specific search or want to file a bug report.
          </p>
          <div className="flex gap-2">
            <input
              type="text"
              value={testerId || 'Loading…'}
              readOnly
              className="flex-1 px-3 py-2 rounded-lg bg-white/[0.04] border border-white/[0.10]
                         text-sm text-base-100 font-mono tracking-tight
                         focus:outline-none select-all"
            />
            <button
              onClick={copyTesterId}
              disabled={!testerId}
              className="px-4 py-2 rounded-lg glass-subtle border border-white/[0.10]
                         text-sm font-medium text-base-200 inline-flex items-center gap-2
                         hover:bg-white/[0.06] transition-colors
                         disabled:opacity-40 disabled:cursor-not-allowed"
              title="Copy to clipboard"
            >
              <Copy size={13} />
              Copy
            </button>
          </div>
        </div>

        {/* Cross-tester learning info */}
        <div className="glass-subtle rounded-xl p-6">
          <div className="flex items-center gap-2 mb-3">
            <RotateCcw size={16} className="text-accent-400" />
            <h2 className="text-sm font-medium">Cross-tester learning</h2>
          </div>
          <p className="text-xs text-base-400 leading-relaxed">
            When your audit folder shares a parent directory with other testers' folders
            (e.g. a shared OneDrive subfolder), the keyword generator automatically reads
            their <code className="text-base-200">market_contributions.jsonl</code> files
            and learns from titles seen across profiles whose tags overlap with yours by
            at least 20%. No setup — just put each tester's audit folder under a common
            parent.
          </p>
        </div>

        {/* Danger zone — irreversible actions live here. Visually offset
            with a red accent so it's hard to miss and harder to misclick. */}
        <div className="rounded-xl p-6 bg-red-500/[0.04] border border-red-500/20">
          <div className="flex items-center gap-2 mb-3">
            <AlertTriangle size={16} className="text-red-400" />
            <h2 className="text-sm font-medium text-red-200">Reset all data</h2>
          </div>
          <p className="text-xs text-base-400 mb-4 leading-relaxed">
            Wipes all local data — runs, scored roles, saved jobs, tracker, profile,
            hidden roles. Cannot be undone. Your tester ID is preserved so your
            Worker budget keeps working.
          </p>
          <button
            onClick={() => setResetModalOpen(true)}
            className="px-4 py-2 rounded-lg bg-red-500/10 border border-red-500/30
                       text-sm font-medium text-red-200
                       hover:bg-red-500/20 hover:border-red-500/50
                       transition-colors"
          >
            Reset all data…
          </button>
        </div>
      </motion.div>

      {/* Confirmation modal — type-to-confirm pattern. The native
          confirm() that History.tsx uses for per-row deletes is fine
          for one row; for "wipe everything" we want explicit muscle-
          memory friction so testers don't blow away their pilot data
          by reflexively hitting Enter. */}
      <AnimatePresence>
        {resetModalOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="fixed inset-0 z-50 flex items-center justify-center
                       bg-black/60 backdrop-blur-sm"
            onClick={closeResetModal}
          >
            <motion.div
              initial={{ opacity: 0, y: 12, scale: 0.96 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 8, scale: 0.98 }}
              transition={{ duration: 0.18, ease: 'easeOut' }}
              onClick={(e) => e.stopPropagation()}
              className="glass rounded-2xl p-7 w-full max-w-md mx-4
                         border border-red-500/30 shadow-2xl"
            >
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-9 h-9 rounded-full bg-red-500/15 border border-red-500/30
                                flex items-center justify-center">
                  <AlertTriangle size={16} className="text-red-300" />
                </div>
                <h3 className="text-base font-semibold text-base-100">Are you sure?</h3>
              </div>

              <p className="text-sm text-base-300 leading-relaxed mb-3">
                This will permanently delete:
              </p>
              <ul className="text-xs text-base-400 leading-relaxed space-y-1 mb-4 ml-1">
                <li>• Run history and all scored roles</li>
                <li>• Saved, applied, and hidden roles</li>
                <li>• Tracker entries and notes</li>
                <li>• Your built profile and keywords</li>
                <li>• Audit JSON files and run-to-run diffs</li>
              </ul>
              <p className="text-xs text-base-400 leading-relaxed mb-5">
                The app will close and reopen on the Welcome screen. Your tester ID
                and Worker budget remain intact.
              </p>

              <label className="block text-xs text-base-400 mb-2">
                Type <code className="text-red-300 font-mono">{RESET_CONFIRM_PHRASE}</code> to confirm:
              </label>
              <input
                type="text"
                value={resetConfirmInput}
                onChange={(e) => setResetConfirmInput(e.target.value)}
                disabled={resetting}
                autoFocus
                className="w-full px-3 py-2 rounded-lg bg-white/[0.04] border border-white/[0.10]
                           text-sm text-base-100 placeholder:text-base-600
                           focus:outline-none focus:border-red-500/50 mb-5
                           disabled:opacity-50"
                placeholder={RESET_CONFIRM_PHRASE}
                onKeyDown={(e) => {
                  if (e.key === 'Escape') closeResetModal()
                  if (
                    e.key === 'Enter' &&
                    resetConfirmInput.trim() === RESET_CONFIRM_PHRASE &&
                    !resetting
                  ) {
                    handleReset()
                  }
                }}
              />

              <div className="flex justify-end gap-2">
                <button
                  onClick={closeResetModal}
                  disabled={resetting}
                  className="px-4 py-2 rounded-lg text-sm
                             text-base-300 hover:bg-white/[0.06]
                             transition-colors disabled:opacity-40"
                >
                  Cancel
                </button>
                <button
                  onClick={handleReset}
                  disabled={resetting || resetConfirmInput.trim() !== RESET_CONFIRM_PHRASE}
                  className="px-4 py-2 rounded-lg text-sm font-medium
                             bg-red-500/15 border border-red-500/40 text-red-200
                             hover:bg-red-500/25 hover:border-red-500/60
                             transition-colors
                             disabled:opacity-40 disabled:cursor-not-allowed
                             disabled:hover:bg-red-500/15 disabled:hover:border-red-500/40
                             flex items-center gap-2"
                >
                  {resetting && <Loader2 size={14} className="animate-spin" />}
                  {resetting ? 'Resetting…' : 'Reset everything'}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
