# Auto-generated by scripts/verify_workday_smart.py
# Each entry: (display_name, base_url, board_path, body_variant)
WORKDAY_TENANTS_VERIFIED = [
    ('Accenture'                   , 'https://accenture.wd103.myworkdayjobs.com'                 , 'AccentureCareers'                      , 'v1_minimal'),  # 2000 jobs
    ('Citi'                        , 'https://citi.wd5.myworkdayjobs.com'                        , '2'                                     , 'v1_minimal'),  # 2000 jobs
    ('PNC'                         , 'https://pnc.wd5.myworkdayjobs.com'                         , 'External'                              , 'v1_minimal'),  # 2000 jobs
    ('Walmart'                     , 'https://walmart.wd5.myworkdayjobs.com'                     , 'WalmartExternal'                       , 'v1_minimal'),  # 2000 jobs
    ('PwC'                         , 'https://pwc.wd3.myworkdayjobs.com'                         , 'Global_Experienced_Careers'            , 'v1_minimal'),  # 1766 jobs
    ('Leidos'                      , 'https://leidos.wd5.myworkdayjobs.com'                      , 'External'                              , 'v1_minimal'),  # 1723 jobs
    ('Booz Allen'                  , 'https://bah.wd1.myworkdayjobs.com'                         , 'BAH_Jobs'                              , 'v1_minimal'),  # 1605 jobs
    ('JLL'                         , 'https://jll.wd1.myworkdayjobs.com'                         , 'jllcareers'                            , 'v1_minimal'),  # 1444 jobs
    ('T-Mobile'                    , 'https://tmobile.wd1.myworkdayjobs.com'                     , 'External'                              , 'v1_minimal'),  # 1380 jobs
    ('Amgen'                       , 'https://amgen.wd1.myworkdayjobs.com'                       , 'Careers'                               , 'v1_minimal'),  # 1234 jobs
    ('Adobe'                       , 'https://adobe.wd5.myworkdayjobs.com'                       , 'external_experienced'                  , 'v1_minimal'),  # 1147 jobs
    ('Capital One'                 , 'https://capitalone.wd12.myworkdayjobs.com'                 , 'Capital_One'                           , 'v1_minimal'),  # 1063 jobs
    ('Truist'                      , 'https://truist.wd1.myworkdayjobs.com'                      , 'Careers'                               , 'v1_minimal'),  # 1008 jobs
    ('CarMax'                      , 'https://carmax.wd1.myworkdayjobs.com'                      , 'External'                              , 'v1_minimal'),  # 926 jobs
    ('Visa'                        , 'https://visa.wd5.myworkdayjobs.com'                        , 'Visa'                                  , 'v1_minimal'),  # 838 jobs
    ('Eli Lilly'                   , 'https://lilly.wd5.myworkdayjobs.com'                       , 'LLY'                                   , 'v1_minimal'),  # 787 jobs
    ('GDIT'                        , 'https://gdit.wd5.myworkdayjobs.com'                        , 'External_Career_Site'                  , 'v1_minimal'),  # 780 jobs
    ('Boeing'                      , 'https://boeing.wd1.myworkdayjobs.com'                      , 'External_Careers'                      , 'v1_minimal'),  # 761 jobs
    ('Intel'                       , 'https://intel.wd1.myworkdayjobs.com'                       , 'External'                              , 'v1_minimal'),  # 704 jobs
    ('Mastercard'                  , 'https://mastercard.wd1.myworkdayjobs.com'                  , 'CorporateCareers'                      , 'v1_minimal'),  # 647 jobs
    ('Prudential'                  , 'https://prudential.wd3.myworkdayjobs.com'                  , 'Prudential'                            , 'v1_minimal'),  # 546 jobs
    ('Salesforce'                  , 'https://salesforce.wd12.myworkdayjobs.com'                 , 'External_Career_Site'                  , 'v1_minimal'),  # 544 jobs
    ('Morgan Stanley'              , 'https://ms.wd5.myworkdayjobs.com'                          , 'External'                              , 'v1_minimal'),  # 469 jobs
    ('3M'                          , 'https://3m.wd1.myworkdayjobs.com'                          , 'Search'                                , 'v1_minimal'),  # 396 jobs
    ('Pfizer'                      , 'https://pfizer.wd1.myworkdayjobs.com'                      , 'PfizerCareers'                         , 'v1_minimal'),  # 357 jobs
    ('Allstate'                    , 'https://allstate.wd5.myworkdayjobs.com'                    , 'Allstate_Careers'                      , 'v1_minimal'),  # 334 jobs
    ('Target'                      , 'https://target.wd5.myworkdayjobs.com'                      , 'targetcareers'                         , 'v1_minimal'),  # 312 jobs
    ('Travelers'                   , 'https://travelers.wd5.myworkdayjobs.com'                   , 'External'                              , 'v1_minimal'),  # 303 jobs
    ('CACI'                        , 'https://caci.wd1.myworkdayjobs.com'                        , 'External'                              , 'v1_minimal'),  # 301 jobs
    ('Gilead'                      , 'https://gilead.wd1.myworkdayjobs.com'                      , 'gileadcareers'                         , 'v1_minimal'),  # 298 jobs
    ('McKesson'                    , 'https://mckesson.wd3.myworkdayjobs.com'                    , 'External_Careers'                      , 'v1_minimal'),  # 286 jobs
    ('Disney'                      , 'https://disney.wd5.myworkdayjobs.com'                      , 'disneycareer'                          , 'v1_minimal'),  # 285 jobs
    ('AIG'                         , 'https://aig.wd1.myworkdayjobs.com'                         , 'aig'                                   , 'v1_minimal'),  # 237 jobs
    ('Old Dominion'                , 'https://odfl.wd1.myworkdayjobs.com'                        , 'Odfl_Careers'                          , 'v1_minimal'),  # 230 jobs
    ('Cisco'                       , 'https://cisco.wd5.myworkdayjobs.com'                       , 'Cisco_Careers'                         , 'v1_minimal'),  # 222 jobs
    ('HP'                          , 'https://hp.wd5.myworkdayjobs.com'                          , 'ExternalCareerSite'                    , 'v1_minimal'),  # 218 jobs
    ('BlackRock'                   , 'https://blackrock.wd1.myworkdayjobs.com'                   , 'BlackRock_Professional'                , 'v1_minimal'),  # 206 jobs
    ('Comcast'                     , 'https://comcast.wd5.myworkdayjobs.com'                     , 'Comcast_Careers'                       , 'v1_minimal'),  # 137 jobs
    ('BDO'                         , 'https://bdo.wd3.myworkdayjobs.com'                         , 'Bdo'                                   , 'v1_minimal'),  # 87 jobs
    ('RAND Corporation'            , 'https://rand.wd5.myworkdayjobs.com'                        , 'External_Career_Site'                  , 'v1_minimal'),  # 2 jobs
]